package utils

const (
	AED = "AED" // United Arab Emirates Dirham
	AFN = "AFN" // Afghan Afghani
	ALL = "ALL" // Albanian Lek
	AMD = "AMD" // Armenian Dram
	ANG = "ANG" // Netherlands Antillean Guilder
	AOA = "AOA" // Angolan Kwanza
	ARS = "ARS" // Argentine Peso
	AUD = "AUD" // Australian Dollar
	AWG = "AWG" // Aruban Florin
	AZN = "AZN" // Azerbaijani Manat
	BAM = "BAM" // Bosnia and Herzegovina Convertible Mark
	BBD = "BBD" // Barbadian Dollar
	BDT = "BDT" // Bangladeshi Taka
	BGN = "BGN" // Bulgarian Lev
	BHD = "BHD" // Bahraini Dinar
	BIF = "BIF" // Burundian Franc
	BMD = "BMD" // Bermudian Dollar
	BND = "BND" // Brunei Dollar
	BOB = "BOB" // Bolivian Boliviano
	BRL = "BRL" // Brazilian Real
	BSD = "BSD" // Bahamian Dollar
	BTC = "BTC" // Bitcoin
	BTN = "BTN" // Bhutanese Ngultrum
	BWP = "BWP" // Botswana Pula
	BYN = "BYN" // Belarusian Ruble
	BYR = "BYR" // Belarusian Ruble (old)
	BZD = "BZD" // Belize Dollar
	CAD = "CAD" // Canadian Dollar
	CDF = "CDF" // Congolese Franc
	CHF = "CHF" // Swiss Franc
	CLP = "CLP" // Chilean Peso
	CNY = "CNY" // Chinese Yuan
	COP = "COP" // Colombian Peso
	CRC = "CRC" // Costa Rican Colón
	CUC = "CUC" // Cuban Convertible Peso
	CUP = "CUP" // Cuban Peso
	CVE = "CVE" // Cape Verdean Escudo
	CZK = "CZK" // Czech Koruna
	DJF = "DJF" // Djiboutian Franc
	DKK = "DKK" // Danish Krone
	DOP = "DOP" // Dominican Peso
	DZD = "DZD" // Algerian Dinar
	EGP = "EGP" // Egyptian Pound
	ERN = "ERN" // Eritrean Nakfa
	ETB = "ETB" // Ethiopian Birr
	EUR = "EUR" // Euro
	FJD = "FJD" // Fijian Dollar
	FKP = "FKP" // Falkland Islands Pound
	GBP = "GBP" // British Pound
	GEL = "GEL" // Georgian Lari
	GGP = "GGP" // Guernsey Pound
	GHS = "GHS" // Ghanaian Cedi
	GIP = "GIP" // Gibraltar Pound
	GMD = "GMD" // Gambian Dalasi
	GNF = "GNF" // Guinean Franc
	GTQ = "GTQ" // Guatemalan Quetzal
	GYD = "GYD" // Guyanese Dollar
	HKD = "HKD" // Hong Kong Dollar
	HNL = "HNL" // Honduran Lempira
	HRK = "HRK" // Croatian Kuna
	HTG = "HTG" // Haitian Gourde
	HUF = "HUF" // Hungarian Forint
	IDR = "IDR" // Indonesian Rupiah
	ILS = "ILS" // Israeli New Shekel
	IMP = "IMP" // Manx pound
	INR = "INR" // Indian Rupee
	IQD = "IQD" // Iraqi Dinar
	IRR = "IRR" // Iranian Rial
	ISK = "ISK" // Icelandic Króna
	JEP = "JEP" // Jersey Pound
	JMD = "JMD" // Jamaican Dollar
	JOD = "JOD" // Jordanian Dinar
	JPY = "JPY" // Japanese Yen
	KES = "KES" // Kenyan Shilling
	KGS = "KGS" // Kyrgyzstani Som
	KHR = "KHR" // Cambodian Riel
	KMF = "KMF" // Comorian Franc
	KPW = "KPW" // North Korean Won
	KRW = "KRW" // South Korean Won
	KWD = "KWD" // Kuwaiti Dinar
	KYD = "KYD" // Cayman Islands Dollar
	KZT = "KZT" // Kazakhstani Tenge
	LAK = "LAK" // Lao Kip
	LBP = "LBP" // Lebanese Pound
	LKR = "LKR" // Sri Lankan Rupee
	LRD = "LRD" // Liberian Dollar
	LSL = "LSL" // Lesotho Loti
	LYD = "LYD" // Libyan Dinar
	MAD = "MAD" // Moroccan Dirham
	MDL = "MDL" // Moldovan Leu
	MGA = "MGA" // Malagasy Ariary
	MKD = "MKD" // Macedonian Denar
	MMK = "MMK" // Myanmar Kyat
	MNT = "MNT" // Mongolian Tögrög
	MOP = "MOP" // Macanese Pataca
	MRO = "MRO" // Mauritanian Ouguiya (old)
	MRU = "MRU" // Mauritanian Ouguiya
	MUR = "MUR" // Mauritian Rupee
	MVR = "MVR" // Maldivian Rufiyaa
	MWK = "MWK" // Malawian Kwacha
	MXN = "MXN" // Mexican Peso
	MYR = "MYR" // Malaysian Ringgit
	MZN = "MZN" // Mozambican Metical
	NAD = "NAD" // Namibian Dollar
	NGN = "NGN" // Nigerian Naira
	NIO = "NIO" // Nicaraguan Córdoba
	NOK = "NOK" // Norwegian Krone
	NPR = "NPR" // Nepalese Rupee
	NZD = "NZD" // New Zealand Dollar
	OMR = "OMR" // Omani Rial
	PAB = "PAB" // Panamanian Balboa
	PEN = "PEN" // Peruvian Sol
	PGK = "PGK" // Papua New Guinean Kina
	PHP = "PHP" // Philippine Peso
	PKR = "PKR" // Pakistani Rupee
	PLN = "PLN" // Polish Złoty
	PYG = "PYG" // Paraguayan Guaraní
	QAR = "QAR" // Qatari Riyal
	RON = "RON" // Romanian Leu
	RSD = "RSD" // Serbian Dinar
	RUB = "RUB" // Russian Ruble
	RWF = "RWF" // Rwandan Franc
	SAR = "SAR" // Saudi Riyal
	SBD = "SBD" // Solomon Islands Dollar
	SCR = "SCR" // Seychellois Rupee
	SDG = "SDG" // Sudanese Pound
	SEK = "SEK" // Swedish Krona
	SGD = "SGD" // Singapore Dollar
	SHP = "SHP" // Saint Helena Pound
	SLL = "SLL" // Sierra Leonean Leone
	SOS = "SOS" // Somali Shilling
	SRD = "SRD" // Surinamese Dollar
	SSP = "SSP" // South Sudanese Pound
	STD = "STD" // São Tomé and Príncipe Dobra (old)
	STN = "STN" // São Tomé and Príncipe Dobra
	SVC = "SVC" // Salvadoran Colón
	SYP = "SYP" // Syrian Pound
	SZL = "SZL" // Swazi Lilangeni
	THB = "THB" // Thai Baht
	TJS = "TJS" // Tajikistani Somoni
	TMT = "TMT" // Turkmenistan Manat
	TND = "TND" // Tunisian Dinar
	TOP = "TOP" // Tongan Paʻanga
	TRY = "TRY" // Turkish Lira
	TTD = "TTD" // Trinidad and Tobago Dollar
	TWD = "TWD" // New Taiwan Dollar
	TZS = "TZS" // Tanzanian Shilling
	UAH = "UAH" // Ukrainian Hryvnia
	UGX = "UGX" // Ugandan Shilling
	USD = "USD" // United States Dollar
	UYU = "UYU" // Uruguayan Peso
	UZS = "UZS" // Uzbekistan Som
	VEF = "VEF" // Venezuelan Bolívar Fuerte (old)
	VES = "VES" // Venezuelan Bolívar Soberano
	VND = "VND" // Vietnamese Đồng
	VUV = "VUV" // Vanuatu Vatu
	WST = "WST" // Samoan Tala
	XAF = "XAF" // Central African CFA Franc
	XAG = "XAG" // Silver Ounce
	XAU = "XAU" // Gold Ounce
	XCD = "XCD" // East Caribbean Dollar
	XDR = "XDR" // Special Drawing Rights
	XOF = "XOF" // West African CFA Franc
	XPD = "XPD" // Palladium Ounce
	XPF = "XPF" // CFP Franc
	XPT = "XPT" // Platinum Ounce
	YER = "YER" // Yemeni Rial
	ZAR = "ZAR" // South African Rand
	ZMW = "ZMW" // Zambian Kwacha
	ZWL = "ZWL" // Zimbabwean Dollar
)

func IsSupportedCurrency(currency string) bool {
	switch currency {
	case AED, AFN, ALL, AMD, ANG, AOA, ARS, AUD, AWG, AZN, BAM, BBD, BDT, BGN, BHD, BIF, BMD, BND, BOB, BRL, BSD, BTC, BTN, BWP, BYN, BYR, BZD, CAD, CDF, CHF, CLP, CNY, COP, CRC, CUC, CUP, CVE, CZK, DJF, DKK, DOP, DZD, EGP, ERN, ETB, EUR, FJD, FKP, GBP, GEL, GGP, GHS, GIP, GMD, GNF, GTQ, GYD, HKD, HNL, HRK, HTG, HUF, IDR, ILS, IMP, INR, IQD, IRR, ISK, JEP, JMD, JOD, JPY, KES, KGS, KHR, KMF, KPW, KRW, KWD, KYD, KZT, LAK, LBP, LKR, LRD, LSL, LYD, MAD, MDL, MGA, MKD, MMK, MNT, MOP, MRO, MRU, MUR, MVR, MWK, MXN, MYR, MZN, NAD, NGN, NIO, NOK, NPR, NZD, OMR, PAB, PEN, PGK, PHP, PKR, PLN, PYG, QAR, RON, RSD, RUB, RWF, SAR, SBD, SCR, SDG, SEK, SGD, SHP, SLL, SOS, SRD, SSP, STD, STN, SVC, SYP, SZL, THB, TJS, TMT, TND, TOP, TRY, TTD, TWD, TZS, UAH, UGX, USD, UYU, UZS, VEF, VES, VND, VUV, WST, XAF, XAG, XAU, XCD, XDR, XOF, XPD, XPF, XPT, YER, ZAR, ZMW, ZWL:
		return true
	default:
		return false
	}
}